# Generated by Django 4.1 on 2022-08-18 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enquery',
        ),
    ]
