# Generated by Django 4.1 on 2022-09-05 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_project_enquery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enquery',
        ),
        migrations.DeleteModel(
            name='Project_Enquery',
        ),
    ]
